services:
  - type: web
    name: promptcraft
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BASE_URL
        value: https://promptcraft-2q3v.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MS_CLIENT_ID
        sync: false
      - key: MS_CLIENT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false
